AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Managed Grafana with SSO (Clean + Production Safe)

Parameters:
  WorkspaceName:
    Type: String
    Default: my-grafana-workspace

  PermissionType:
    Type: String
    Default: SERVICE_MANAGED
    AllowedValues:
      - SERVICE_MANAGED
      - CUSTOMER_MANAGED

Resources:

  GrafanaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub grafana-service-role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: grafana.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess
  GrafanaSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: grafana-notifications
  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      Name: !Ref WorkspaceName
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      PermissionType: !Ref PermissionType
      RoleArn: !GetAtt GrafanaServiceRole.Arn

      DataSources:
        - CLOUDWATCH
        - XRAY

      NotificationDestinations:
        - !Ref GrafanaSNSTopic

      PluginAdminEnabled: true

Outputs:

  WorkspaceId:
    Description: Grafana Workspace ID
    Value: !Ref GrafanaWorkspace

  GrafanaURL:
    Description: Grafana Endpoint URL
    Value: !GetAtt GrafanaWorkspace.Endpoint
